### ISSUE TITLE
Build crashes with a "corrupted class path" error after upgrading to Scalafmt 3.7.16

### ISSUE THREAD

**Issue by odisseus** [scalameta/sbt-scalafmt#290] opened 2023-11-16 13:47 UTC
I have a SBT project which works well with Scalafmt 3.7.15. When attempting to upgrade to 3.7.16, I get the following error:
```
$ sbt scalafmtCheckAll
[info] welcome to sbt 1.9.7 (Oracle Corporation Java 19.0.2)
...
[error] (driver_2_13 / Compile / scalafmtCheck) org.scalafmt.sbt.ScalafmtSbtReporter$ScalafmtSbtError: scalafmt: [v3.7.16] corrupted class path: [/lots/of/paths/here ...][[~/devel/ide-probe/.scalafmt.conf]]
```

The same problem can be seen [here](https://github.com/VirtusLab/ide-probe/actions/runs/6838271464/job/18708028003?pr=396) in CI.

Interestingly, the Coursier distribution of Scalafmt seems to work without error:
```
$ scalafmt
Reformatting...
  100.0% [##########] 247 source files formatted
```

My configuration file looks like this:
```
version = "3.7.16"
project.git = true
align = most
runner.dialect = scala213
align.arrowEnumeratorGenerator = true
danglingParentheses.preset = true
docstrings.style = asterisk
maxColumn = 120

rewrite.rules = [AvoidInfix]
```

**Comment by kitbellew** [comment] 2023-11-16 15:41
duplicate of scalameta/scalafmt#3689

**Closed by kitbellew** 2023-11-16 15:41 UTC
